### ISSUE TITLE
i18n Fallback Language

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#114]
fallbackNS is an option for custom types. https://www.i18next.com/overview/typescript#custom-type-options

This would default to a given namespace if a translation key is not found. I think it would be prudent to maintain a fallback namespace that falls back to English.

i.e. There's a missing key in the `es.json` file, so that specific word/translation fallsback to English.

**This may already happen but I want to ensure it with testing so am creating the issue.**

**Comment by wbobeirne** [comment]
That's actually not how `fallbackNS` works. Namespaces in i18next are a way of separating out translations into multiple files. You can access namespaces by doing `t('namespace:translation.key')`. The `fallbackNS` key just works by making it so that if one namespace is missing the key, it'll check a different namespace.

This could be useful if we for instance were to separate translations between Leader and Follower into two namespaces. You could have different user roles have different translations, but if a key was missing in one, it could look to another namespace for the key.

For languages, you need to configure `fallbackLng`: https://www.i18next.com/principles/fallback#fallback-to-different-languages.

**Comment by benalleng** [comment]
currently the ui fallbackLng is initialized in the `utils/i18n.tsx` as `fallbackLng: 'en-US',`

when deleting any key not in `en.json` the text shows the English instead.

![image](https://github.com/fedimint/ui/assets/108441023/09b1c125-85ec-4bb0-aabb-44523bc999de)

if there is not a key in `es.json` or `en.json` the key will be shown

![image](https://github.com/fedimint/ui/assets/108441023/9b55758c-cca4-41fa-b490-4eefb8bf3be3)

**Comment by wbobeirne** [comment]
Looks like this was added in #99, closing
