### ISSUE TITLE
Error connecting federation: bad payload on /connect-fed

### ISSUE THREAD

**Issue by otech47** [fedimint/ui#135]
![Screenshot 2023-08-07 at 5 38 57 PM](https://github.com/fedimint/ui/assets/4914611/d32c7961-2181-42a7-85fd-15c96334d0ab)

need to update API handler to use new fields: https://github.com/fedimint/fedimint/pull/2882/files#diff-ced31c945d33239dd853e475be96e60061f52213604182319c123ccfc24cf67cL24

@okjodom

**Comment by okjodom** [comment]
https://github.com/fedimint/fedimint/pull/2882 is a rename that doesn't change any fields in encoded `InviteCode`. I suspect your setup has older versions of Fedimint nodes and need to update via `docker pull`. You may have to delete local docker images first, then just run mprocs to full fresh ones.

PS: this also highlighted another bug in connect-fed, fixed by https://github.com/fedimint/ui/pull/136

**Comment by otech47** [comment]
also can confirm that running `docker exec gateway_gatewayd_1 gateway-cli --rpcpassword <password> connect-fed <INVITE_CODE>` does work so that's why i thought it might be a UI/API interface issue
