### ISSUE TITLE
"view on mempool.space" and "view on amboss" don't work on mutinynet

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#242]
"view on mempool.space" should point to mutinynet.com. Since I don't think there is a node explorer on mutinynet, I think we should just hide the "view on amboss" button.

![image](https://github.com/fedimint/ui/assets/4335621/f5c681c4-fd64-49de-8c9d-7a3996d633a8)

**Comment by wbobeirne** [comment]
Mempool has its own node explorer so we could just use that instead (on mutinynet or always)

We should probably figure out links for testnet too while we're here.

**Comment by okjodom** [comment]
Easy fix after https://github.com/fedimint/fedimint/pull/3455 which also exposes network on gateway info

**Comment by justinmoon** [comment]
> Easy fix after https://github.com/fedimint/fedimint/pull/3455 which also exposes network on gateway info

Will we backport this? If we do, how will we manage the change to "gateway info" object?

**Comment by okjodom** [comment]
We need a backport. Since the change **introduces** a new, nullable property to `gateway info`, it's back compatible and the UI can consume the new property when available in updated gatewayds, and assume it's not set otherwise.

Perhaps the UI should hide these links when info.network is not available
