### ISSUE TITLE
CopyInput doesn't allow viewing hyper-long strings

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/ui#27]
connectionCode in apps/guardian-ui/src/components/FederationDashboard.tsx is an example. The connection info string is very long cannot be viewed in full in the CopyInput element.

**Comment by wbobeirne** [comment]
I think this is fine as it's a pretty common UI pattern and it's fully accessible since all the text is rendered in the DOM, it's just obscured due to its length. You can reveal it all by using a horizontal scroll input, or by clicking and dragging to reveal more.

The one thing that might be worth doing is ellipsizing the text, to make it clear that there's more. Before / after:

<img width="379" alt="Screenshot 2023-07-07 at 11 52 28 AM" src="https://github.com/fedimint/ui/assets/649992/849aa3f9-fdf6-4ce2-af59-87dd15ca3ad9">
<img width="385" alt="Screenshot 2023-07-07 at 11 53 24 AM" src="https://github.com/fedimint/ui/assets/649992/a662a328-dc27-4f27-981e-e489c50bc4f3">

**Comment by wbobeirne** [comment]
Marking this as closed by #168 since it adds the ellipsizing of the input. This should hopefully make it clear that there's more text in there and that you can use typical inputs that your OS supports to view the rest of it.
