### ISSUE TITLE
Closing Mprocs hangs

### ISSUE THREAD

**Issue by alexlwn123** [fedimint/ui#495]
When killing `just mprocs` by hitting `q`, the "start servers" shell hangs... After hitting CTRL-c on the shell, it closes normally.

**Comment by Kodylow** [comment]
when you just mprocs it uses docker, the hanging is waiting for the containers to close out.

Use nix instead, get into the nix develop shell then use `just guardian` for the setup process or `just gateway` to start an already configured 4 guardian fed and have the gateways running and attached

could probably use some better documentation around it though, know it's confusing since fedimint just mprocs is what you always do but you shouldn't do it here

**Comment by Kodylow** [comment]
https://github.com/fedimint/ui/pull/497
