### ISSUE TITLE
"Propose new metadata" button disabled

### ISSUE THREAD

**Issue by hensg** [fedimint/ui#554]
I'm running a "Solo Mode Federation" and would like to change the name of my federation. However, the "Propose new metadata" button is disabled. Should it really say "Propose," considering the federation is in Solo Mode? Wouldn't "Update metadata" make more sense? It feels odd to "propose" something when there's no one to propose it to.

![image](https://github.com/user-attachments/assets/b21a4473-ebe7-4156-992b-f4aa85439519)

**Comment by hensg** [comment]
Actually, it was enabled after entering the federation icon URL. Is it really required?

**Comment by kleyberthsantos** [comment]
I see that the "Propose New Metadata" label is generalized for both multi-guardian and single-guardian federations.

- Do you suggest that "Update Metadata" be a change to the button label or that logic be added so that the change from "Propose New Metadata" to "Update Metadata" is only available in Solo Mode Federation?

- The button is enabled as long as all fields are filled, and it also checks that the Icon url is an image, would you like the button to keep the same logic but be enabled without the Icon url?

If the answer is yes, I'd liked to say I agree.

**Comment by kleysc** [comment]
Hi @hensg ! I have implemented metadata button label differentiation for federations in single mode. The registration request is now ready for review.

The implementation:
- Changes button text to "Update Metadata" in single mode
- Maintains "Propose New Metadata" for federations with multiple gatekeepers
- Determines single mode by checking the number of API endpoints

I would appreciate your review and feedback.

Thank you in advance for your time!

PR https://github.com/fedimint/ui/pull/588

**Comment by alexlwn123** [comment]
Thanks for the contribution @kleysc! 

Merged https://github.com/fedimint/ui/pull/588, so closing this issue as completed.
